- name: Install Nginx
  hosts: local
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: statrt Nginx
      ansible.builtin.service:
        name: nginx
        state: statrt
        enable: yes