- name: condition demo
  hosts: local
  vars:
    NUMBER: 50
  tasks:
  - name: print if the number  is less then or equal to 100
  ansible.builtin.debug:
    msg: "given number {{ NUMBER }} is less than or equal to 100"
    when: <= 100

- name: print if the number  is grater then or equal to 100
  ansible.builtin.debug:
    msg: "given number {{ NUMBER }} is grater than 
    when: NUMNER > 100