- name: install package
  hosts: frontend
  tasks:
  - name: install packages
    ansible.builttin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loops:
    - { name: 'mysql' , state: 'present'} 
    - { name: 'nginx' , state: 'absent'}
    - { name: 'zip' , state: 'absent'}
