- name: functions
  hosts: frontend
  become: yes
  vars:
    fruits: "apple,banana,orange"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: " {{ fruits | default }}"
  
  - name: check undefined variable
    ansible.builtin.split :
      msg: "{{ fruits | split(',') }}"